server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:

        - id: test-service
          uri: lb://test-service
          predicates:
            - Path=/test/**

        - id: auth-service-public
          uri: lb://auth-service
          predicates:
            - Path=/auth/login,/auth/register

        - id: auth-service-secure
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - name: JwtGatewayFilter

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - name: JwtGatewayFilter

        - id: mentor-service
          uri: lb://mentor-service
          predicates:
            - Path=/mentors/**
          filters:
            - name: JwtGatewayFilter

        - id: skill-service
          uri: lb://skill-service
          predicates:
            - Path=/skills/**
          filters:
            - name: JwtGatewayFilter

        - id: session-service
          uri: lb://session-service
          predicates:
            - Path=/sessions/**
          filters:
            - name: JwtGatewayFilter

        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/reviews/**
          filters:
            - name: JwtGatewayFilter
