server:
  port: 8083

spring:
  application:
    name: mentor-service

  datasource:
    url: jdbc:mysql://localhost:3306/skillsync_mentor
    username: javauser
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
