server:
  port: 8087

spring:
  application:
    name: notification-service

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  mail:
    host: smtp.gmail.com
    port: 587
    username: ashutosh12501@gmail.com
    password: kxjrljsibkmhqvau
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
