server:
  port: 8086

spring:
  application:
    name: review-service

  datasource:
    url: jdbc:mysql://localhost:3306/skillsync_review?useSSL=false&serverTimezone=UTC
    username: javauser
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
